version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: env/app/Dockerfile
    container_name: app
    env_file:
      - .env
    volumes:
      - ./app:/application/app
      - ./database:/application/database
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: env/nginx/Dockerfile
    container_name: nginx
    environment:
      APP_PORT: ${APP_PORT}
      NGINX_PORT: ${NGINX_PORT}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  postgres_data:
